### ISSUE TITLE
Tutorial should have color-coded icons for terminal, irb, rails s, rails c, and text editor

### ISSUE THREAD

**Issue by brigittewarner** [bmoreonrails/rails_tutorial#105]
Need to upload these assets and then place them appropriately alongside instructions in tutorial
- [ ] Command Line - black hexon (CL)
- [ ] IRB - red hexagon (RB)
- [ ] Rails Server - purple hexagon (RS)
- [ ] Rails Console - yellow (RC)
- [ ] Text Editor - green (E)

**Comment by brigittewarner** [comment]
Instead of assets, one could simply use the code from this codepen to drop the indicators in (colors could easily be changed to match chosen color-scheme.  Also, this is more accessible:

https://codepen.io/brigittewarner/pen/PWRPEy?editors=1100

![image](https://cloud.githubusercontent.com/assets/5412015/22515409/5d6e6fa6-e870-11e6-84be-5672b56ced0d.png)

**Comment by alimi** [comment]
Thanks for opening this issue! I'm gonna close this issue for now while we think through different ways we can make the tutorial more accessible.
