### ISSUE TITLE
"Reviews" missing "s" in Ch. 9 Step 40 and Ch. 11 Step 20

### ISSUE THREAD

**Issue by ghost** [bmoreonrails/rails_tutorial#148]
Chapter 9, Step #40:
Spend some time playing around with this relationship. You can do things like my_first_book.reviews.first or my_first_book.review.pluck(:body).
like my_first_book.reviews.first or my_first_book.review.pluck(:body).
To find a complete list of all the things you can do, take a look at the documentation here.

The second command should be "my_first_book.reviews.pluck(:body)"

[Note the plural of "review" instead of the singular.] 

Also, in Chapter 11, Step 20: http://localhost:3000/books/1/review/new should read http://localhost:3000/books/1/reviews/new (notice the "s" after reviews).

**Comment by latazzajones** [comment]
Thanks for posting this @vsard! Hopefully we can fix these in the next week or so!

**Comment by ghost** [comment]
@latazzajones , I'd be happy to make the corrections myself but I've never contributed to a project before so I'm not sure how to do the whole pull request and branching, etc... If you want to tutor me in that for this, I'd be happy to do the work.

**Comment by latazzajones** [comment]
Great! I'll coordinate with you tomorrow and we can find a time to work on it together.

**Comment by ghost** [comment]
I forked the branch, made the corrections and did a pull request. Hopefully I did them correctly.

**Comment by alimi** [comment]
Fixed in ad0f0e678a218f453d83a0ce0ebe55bbc3ed7178 and 9920fcbf692adfd8a370fdd1127b4829f1579bf6.
