### ISSUE TITLE
Link the protip in chapter 1 to the install instructions

### ISSUE THREAD

**Issue by latazzajones** [bmoreonrails/rails_tutorial#21]
There's a link in one of the protips that's supposed to go to the install instructions ... it doesn't link to anything right now.

**Comment by solipet** [comment]
This will be trivial once the installation guides are merged in (PR #4)

**Comment by latazzajones** [comment]
😝 I wrote it down since it's exactly the kind of thing I'd forget to do.

**Comment by solipet** [comment]
Done in PR #45

**Comment by latazzajones** [comment]
Thanks!!
