### ISSUE TITLE
Add a search tool

### ISSUE THREAD

**Issue by latazzajones** [bmoreonrails/rails_tutorial#25]
There are some great js based search tools that cram all the site content into a json blob so that it can be searched even though the site is static. Our deployment process will support this type of static search. Let's add it because we love our students. 

Here's one option: http://jekyll.tips/jekyll-casts/jekyll-search-using-lunr-js/

There are others out there. 

Here's what the design has - feel free to make adjustments if you need to but this was the original design goal: 

<img width="1253" alt="screen shot 2017-01-06 at 8 28 38 am" src="https://cloud.githubusercontent.com/assets/6585221/21719192/5d672dee-d3ea-11e6-8a70-148507bd00e1.png">

**Comment by nerdEd** [comment]
This is functionally complete on the "add-search" branch [here](https://github.com/bmoreonrails/rails_tutorial/tree/add-search), but it will need someone with more CSS/layout mojo than I to get it across the finish line. @jjulian? @michellemartir? Specifically:

- [ ] Add search icon to text input
- [ ] Make sure that I didn't completely ruin the responsive layout

@latazzajones do we have basic mocks of what the search result screen should look like?

**Comment by latazzajones** [comment]
@nerdEd we don't have any mocks for the search tool but sounds like you've pinged all the right people because - css and design are not my friends.

**Comment by latazzajones** [comment]
@nerdEd I'm also happy to merge it if it's functioning then make another story for cleaning up the styles ... either way - let me know.

**Comment by PaulOstazeski** [comment]
Here's a search icon. 
[search_icon.zip](https://github.com/bmoreonrails/rails_tutorial/files/709920/search_icon.zip)
