### ISSUE TITLE
Come up with a menu solution that's not a hamburger

### ISSUE THREAD

**Issue by latazzajones** [bmoreonrails/rails_tutorial#31]
Because we're better than this.

**Comment by latazzajones** [comment]
Michelle's working on this!

**Comment by michellemartir** [comment]
For real, out of curiosity question: y no burber?

**Comment by latazzajones** [comment]
tehe - this isn't super high priority. Honestly, we could just scrap it. Mostly a friend was complaining about them the other day and I thought we could think about other, more user-responsive solutions. But maybe lets do this after this years workshop if we decide to do it at all ..

**Comment by alimi** [comment]
Closing because @latazzajones said so.
