### ISSUE TITLE
Fix the steps container's resizing issues

### ISSUE THREAD

**Issue by latazzajones** [bmoreonrails/rails_tutorial#34]
CSS is my enemy. The steps divs should look like this for tablet and desktop: 

<img width="300" alt="screen shot 2017-01-06 at 9 30 19 am" src="https://cloud.githubusercontent.com/assets/6585221/21720740/cd639008-d3f2-11e6-9e24-df4411f81209.png">

Then they should stack nicely - right now the white of the list segment is wrapping around the highlight box but they should both take up the full width of the parent steps div. Here's what it looks like now: 

<img width="300" alt="screen shot 2017-01-06 at 9 30 31 am" src="https://cloud.githubusercontent.com/assets/6585221/21720759/f26c374c-d3f2-11e6-91de-28213159be62.png">

Also - on larger screens the two child divs pull apart with a gutter between them - that shouldn't happen. Maybe we can just prevent the content div from going over a certain width so that we don't have to worry about large screens.

**Comment by alexfu** [comment]
@latazzajones what is this supposed to look like?

**Comment by latazzajones** [comment]
@alexfu ^^ I added some details.
