### ISSUE TITLE
Finalize install instructions

### ISSUE THREAD

**Issue by latazzajones** [bmoreonrails/rails_tutorial#41]
@solipet I'm not going to review the install instructions. I trust ya'll to get this looking sharp and ready to go. Just ping me when you feel good about them and I'll merge them for you since master is protected. 

If ya'll want more eyes on them ping people in slack and basecamp.  If you don't mind, it'd be super helpful if you could merge them together into one pr when you feel like they're ready.

**Comment by alimi** [comment]
![tenor](https://cloud.githubusercontent.com/assets/772925/25254847/c058c798-25f5-11e7-8257-e64caf0b7943.gif)
