### ISSUE TITLE
Style the landing page. 

### ISSUE THREAD

**Issue by latazzajones** [bmoreonrails/rails_tutorial#53]
We don't have a design for the tutorial landing page :-(  Right now it looks like this: 

<img width="500" alt="screen shot 2017-01-07 at 9 02 31 pm" src="https://cloud.githubusercontent.com/assets/6585221/21746699/97154250-d51c-11e6-8df1-95431d0c4fa2.png">

Totally depressing. It doesn't have to be crazy - just a little more inspiring.

**Comment by latazzajones** [comment]
addressed in pr #55

**Comment by latazzajones** [comment]
Michelle will do some more work on this.

**Comment by latazzajones** [comment]
@michellemartir hey! how's it going? let me know if you'd like any help with these and I can recruit :)

**Comment by angeliquejw** [comment]
Willing to assist here, if additional help would be beneficial.

**Comment by latazzajones** [comment]
@angeliquejw omg the one thing I desperately need help with if you're willing is fixing the footer. It's supposed to stay at the bottom of the page and under the fold + at the bottom if the page scrolls. It's passable on small screens but totally not passable on bigger ones. Here's a link to the branch where I started trying to fix it https://github.com/bmoreonrails/rails_tutorial/tree/footer_style

**Comment by angeliquejw** [comment]
Working on this now @latazzajones. I'm assuming you just want a sticky bottom footer (ie, it's forced to the bottom even if the page content is not full-height), not fixed bottom (ie, it's always the bottom 80px of the page, locked into place). Should have a fix available soon.

**Comment by latazzajones** [comment]
I'm closing this. We've made the landing page pretty passable :-)
