### ISSUE TITLE
style the footer

### ISSUE THREAD

**Issue by latazzajones** [bmoreonrails/rails_tutorial#65]
I'd like to have the Bmore on rails logo and the icons for the tutorial github repo, and our twitter - [@bmoreonrails](https://twitter.com/bmoreonrails)

The Bmore On Rails logo can be found here: https://github.com/bmoreonrails/bmoreonrails-media/blob/master/logos/ruby_300.png

**Comment by michellemartir** [comment]
I can also put a nice subtle background illustration at the bottom too :) but I think that's low priority until the bulk of CSS is done

**Comment by latazzajones** [comment]
ooh! that could be lovely!

**Comment by latazzajones** [comment]
@michellemartir hey! how's it going? let me know if you'd like any help with these and I can recruit :)
