### ISSUE TITLE
broken image between step 20 and 21 in chapter 1

### ISSUE THREAD

**Issue by nerdEd** [bmoreonrails/rails_tutorial#99]
<img width="1257" alt="screen shot 2017-01-31 at 8 01 16 pm" src="https://cloud.githubusercontent.com/assets/1726/22491228/16d33a8e-e7f0-11e6-9e59-3105679dec0e.png">

**Comment by latazzajones** [comment]
hmmmm - it looks like it's there. We'll keep an eye on this and re open if we get more complaints.
